// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestCaseDashboard.Data;

#nullable disable

namespace TestCaseDashboard.Migrations
{
    [DbContext(typeof(mydatabaseContext))]
    partial class mydatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Buglist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<Guid>("Testcaseid")
                        .HasColumnType("uuid")
                        .HasColumnName("testcaseid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("Testcaseid");

                    b.ToTable("buglist", "public", t =>
                        {
                            t.HasTrigger("buglist_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("ProjectSource")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("Projectname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("projectname");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.ToTable("project", "public", t =>
                        {
                            t.HasTrigger("project_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.ProjectTeammember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("Projectid")
                        .HasColumnType("uuid")
                        .HasColumnName("projectid");

                    b.Property<Guid>("Teammemberid")
                        .HasColumnType("uuid")
                        .HasColumnName("teammemberid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("Projectid");

                    b.HasIndex("Teammemberid");

                    b.ToTable("project_teammember", "public", t =>
                        {
                            t.HasTrigger("project_teammember_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Teammember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.ToTable("teammember", "public", t =>
                        {
                            t.HasTrigger("teammember_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Testcase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Function")
                        .HasColumnType("text")
                        .HasColumnName("function");

                    b.Property<Guid>("Projectid")
                        .HasColumnType("uuid")
                        .HasColumnName("projectid");

                    b.Property<string>("Screen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("screen");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("Projectid");

                    b.ToTable("testcase", "public", t =>
                        {
                            t.HasTrigger("testcase_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.TestcaseTeammember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("Teammemberid")
                        .HasColumnType("uuid")
                        .HasColumnName("teammemberid");

                    b.Property<int>("TestStatus")
                        .HasColumnType("integer")
                        .HasColumnName("testStatus");

                    b.Property<Guid>("Testcaseid")
                        .HasColumnType("uuid")
                        .HasColumnName("testcaseid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("Teammemberid");

                    b.HasIndex("Testcaseid");

                    b.ToTable("testcase_teammember", "public", t =>
                        {
                            t.HasTrigger("testcase_teammember_Trigger");
                        });
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Buglist", b =>
                {
                    b.HasOne("TestCaseDashboard.Models.mydatabase.Testcase", "Testcase")
                        .WithMany("Buglists")
                        .HasForeignKey("Testcaseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Testcase");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.ProjectTeammember", b =>
                {
                    b.HasOne("TestCaseDashboard.Models.mydatabase.Project", "Project")
                        .WithMany("ProjectTeammembers")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestCaseDashboard.Models.mydatabase.Teammember", "Teammember")
                        .WithMany("ProjectTeammembers")
                        .HasForeignKey("Teammemberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Teammember");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Testcase", b =>
                {
                    b.HasOne("TestCaseDashboard.Models.mydatabase.Project", "Project")
                        .WithMany("Testcases")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.TestcaseTeammember", b =>
                {
                    b.HasOne("TestCaseDashboard.Models.mydatabase.Teammember", "Teammember")
                        .WithMany("TestcaseTeammembers")
                        .HasForeignKey("Teammemberid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestCaseDashboard.Models.mydatabase.Testcase", "Testcase")
                        .WithMany("TestcaseTeammembers")
                        .HasForeignKey("Testcaseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teammember");

                    b.Navigation("Testcase");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Project", b =>
                {
                    b.Navigation("ProjectTeammembers");

                    b.Navigation("Testcases");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Teammember", b =>
                {
                    b.Navigation("ProjectTeammembers");

                    b.Navigation("TestcaseTeammembers");
                });

            modelBuilder.Entity("TestCaseDashboard.Models.mydatabase.Testcase", b =>
                {
                    b.Navigation("Buglists");

                    b.Navigation("TestcaseTeammembers");
                });
#pragma warning restore 612, 618
        }
    }
}
